### ISSUE TITLE
need trained model

### ISSUE THREAD

**Issue by simmed00** [CSUBioGroup/PGMG#1]
Thanks for sharing code for the great works. Could you also provide the trained model? Without that I cannot run the notebook file. Thank you in advance.

**Comment by CSUBioGroup** [comment]
Hi @simmed00, sorry for the late reply. We have updated the generation code to make it easier to use and also provide the model weights in the [release page](https://github.com/CSUBioGroup/PGMG/releases/tag/v1.0). 

Please let me know if you have any further quesions.
