### ISSUE TITLE
RuntimeError: CUDA error: unspecified launch failure

### ISSUE THREAD

**Issue by zyrlia1018** [CSUBioGroup/PGMG#3]
inputs, input_mask, pp_graphs, mappings, targets, *others = [i.to('cuda:0') for i in batch_data]

代码执行到这一行的时候会报错，无法将数据从cpu传输到cuda上。但是我取出inputs, input_mask在命令行传给cuda就可以。

**Comment by zyrlia1018** [comment]
Downgrading pytorch can solve this problem. I can run it with torch version 1.21. Also be sure to pay attention to the Numpy version and try to use 1.23.5.

**Comment by CSUBioGroup** [comment]
@zyrlia1018 Thanks for sharing your solution~
