### ISSUE TITLE
.posp file format

### ISSUE THREAD

**Issue by wenchangzhou-qtx** [CSUBioGroup/PGMG#4]
Hey @CSUBioGroup,

Very nice implementation! Regarding the .posp format, they are the 3D coordinates of the pharmacophore right? For hydrogen bond donor or acceptor I guess it's easy, I can just put the position of the atoms that are involved in hydrogen bond. When it comes to aromatic rings, should I put the position of the center of mass of the ring into .posp file?

Thanks,

**Comment by CSUBioGroup** [comment]
Hi @wenchangzhou-qtx 

Certainly, the .posp format represents the 3D coordinates of the pharmacophore. When it comes to hydrogen bond donors or acceptors, it's correct to place the positions of the atoms directly involved in the hydrogen bond. As for aromatic rings, you can use the average coordinates of the heavy atoms involved in forming the aromatic ring.

It's also worth to note that PGMG is currently trained under the shortest-path distances. You might want to consider using the .edgep format for improved performance, which effectively represents pharmacophore hypotheses based on shortest-path distances.

We're delighted to see your interest in PGMG. I'm closing this issue now, but if you have any more questions or need further assistance, please feel free to reopen it.

zhm
