### ISSUE TITLE
Training output stop updating locally

### ISSUE THREAD

**Issue by kolmorgan** [CSUBioGroup/PGMG#5]
I'm using Ubuntu22.04 with RTX4090 and AMD 7950X. I installed the PGMG and trained the model using your uploaded training data. After two days of training, the output file stayed at line 120804 with 
`29%|██▊       | 1168/4096 [01:17<03:40, 13.27it/s]`
`40%|████      | 1647/4096 [01:25<02:15, 18.05it/s]`
`40%|████      | 1647/4096 [01:37<02:15, 18.05it/s]` and stopped update after 6h from the execution
and now the GPU utility fluctuated at 1% with GPU memory of 15210MB. I'm not an expert in this, so I'm unsure if there's something wrong with my training or if it's behaving normally?

**Comment by CSUBioGroup** [comment]
Could you provide with more descptions like in which epoch does it stopped?

**Comment by CSUBioGroup** [comment]
Hi, @kolmorgan . In which epoch did it stop? Could you please show me the contents of the output directory? 

Besides, you can first try resuming training by modifying the following lines in the training script.
```python
    init_epoch = 0  # eg. 16
    reload_path = None  # eg. './output/chembl_test/rs_mapping/fold0_epoch16.pth'
```

**Comment by kolmorgan** [comment]
It ended at 12th epoch. To be specific, there were no training threads after the output of training stopped update, but the process in GPU seemed continuing with high memory usage and rarely GPU utility. So I guess it stopped abnormally.
![Screenshot 2023-10-27 at 20-55-22](https://github.com/CSUBioGroup/PGMG/assets/49088089/100fb246-a510-4ada-a122-545d658f9404)

Thanks for the reply, I'll try to resume the training.

**Comment by CSUBioGroup** [comment]
The generation test starts at 12 epoch. 

```
    skip_gen_test = 12  # skip saving and track Validity for `skip_gen_test` epochs
```

So probably it is the generation test that opens lots of threads that caused the problem. 

Maybe you can try to increase `ulimit` in your shell?

**Comment by kolmorgan** [comment]
Thanks, I have modified the 
    'init_epoch = 12  # e.g., 16
    reload_path = '~/PGMG-main/train_output/rs_mapping/fold0_epoch12.pth'  # e.g., './output/chembl_test/rs_mapping/fold0_epoch16.pth' in the training script and set the ulimit -n 1048576, but the CPU threads still stopped and the file in the new output directory are the same as before...

**Comment by CSUBioGroup** [comment]
@kolmorgan, I'll look into this. In the meantime, a temporary fix could be to disable the generation test by commenting line 538 of `train_chembl_baseline.py`.
```python
#            mean_match_score = test_generate(gen_loader, model, epoch)
```

**Comment by kolmorgan** [comment]
Thanks, I'll try it again.

**Comment by kolmorgan** [comment]
After trying what you said, it seems that the training was complete successfully now, at least there was no error message. 
![截图 2023-11-06 08-56-39](https://github.com/CSUBioGroup/PGMG/assets/49088089/9161347c-dbb7-4fd6-a83d-761bc38d8c4b)
If I want to generate molecules using my own .edgep file, is it right to do that by `python generate.py --n_mol 10000 --device cuda --filter --batch_size 128 --seed 21 lig/ lig/out/ train_outputnew/rs_mapping/fold0_epoch32.pth train_outputnew/rs_mapping/tokenizer_r_iso.pkl` ? Please forgive my unfamiliarity with DL. Also, I have another question. The input file of pharmacophore is either .edgep of .posp file, will it be able to generate more accurate molecules when using both files? Moreover, will there be pharmacophore type of anion in the future?

**Comment by kolmorgan** [comment]
I have tried the four pharmacophores and it worked, but when I tried the 13 pharmacophores, an error message showed.
`python generate.py --n_mol 10000 --device cuda --filter --batch_size 128 --seed 31 lu_3/lu3.edgep lu_3/out/ train_outputnew/rs_mapping/fold0_epoch32.pth train_outputnew/rs_mapping/tokenizer_r_iso.pkl 
WARNING: parameter(s) not used: 
<All keys matched successfully>
  0%|                                                    | 0/79 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "generate.py", line 94, in <module>
    res.extend(tokenizer.get_text(model.generate(g_batch)))
  File "/home/host/anaconda3/envs/pgmg/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/host/PGMG-main/model/pgmg.py", line 279, in generate
    vv, vvs, pp_mask = self.process_p(pp_graphs)
  File "/home/host/PGMG-main/model/pgmg.py", line 161, in process_p
    vv2[:vv.shape[0], :, :] = vv
RuntimeError: The expanded size of the tensor (8) must match the existing size (13) at non-singleton dimension 0.  Target sizes: [8, 128, 384].  Tensor sizes: [13, 128, 384]
`
Is there anything I can do to fix it? Thanks

**Comment by CSUBioGroup** [comment]
Hi @kolmorgan, regarding your previous question about the file format, please refer to my colleague's response in issue #4 .

As for the error message, the current model only supports up to 8 pharmacophore elements in a hypothesis.

> The current model only support a maximum of 8 pharmacophore points in a single hypotheis. If you want to increase the maximum number, a possible way is to re-train the model with increased number of randomly selected pharmacophore elements and a larger MAX_NUM_PP_GRAPHS.

Adding the anion type could also be achieved by making small modifications to the code, specifically lines 38 and 128-130 in `smiles2ppgraph.py` and line 49 in `train_chembl_baseline.py`.

Anions were not incorporated into the current model since they are relatively uncommon in the ChEMBL training data used. Similarly, the limit on the maximum number of pharmacophore points was determined based on the data. However, I appreciate you bringing up these aspects as potential areas for improvement. As my background is primarily on the computational side, additional details around use cases where anions or more pharmacophore points are needed would be very helpful for considering future enhancements. Please feel free to open a new issue to further discuss this. 

I'm closing the current issue now for the original issue is temperally fixed.

**Comment by kolmorgan** [comment]
Can you please share me the modified version or tell me how to modify the code to change the pharmacophore to a number like 13? I'm not an expert in python and DL, and I don't know how to change them without errors or problems. Thanks.
