### ISSUE TITLE
Generate pharmacophore files from SMILES

### ISSUE THREAD

**Issue by miquelduranfrigola** [CSUBioGroup/PGMG#7]
Hello!

Thanks for very nice work and fantastic code.

I am interested in your script `utils/smiles2ppgraph.py`. In particular, I would like to create a `.posp` or `.edgep` file based on the graph generated by this script.

Could you offer some guidance? Any help will be greatly appreciated.

Thanks in advance.

**Comment by CSUBioGroup** [comment]
Hi, @miquelduranfrigola. I went ahead and wrote a function to generate a `.edgep` file from a given graph. One thing to note is that the sizes of each pharmacophore elements are not specified in either the `.posp` or `.edgep` file formats. These sizes are inferred dynamically during model inference. 

Here is the code:

```python
def export_ep_text(g: dgl.DGLGraph, file_path: Optional[Path] = None):
    """
    transfer a given DGLGraph into text using .edgep format
    """

    g = g.cpu()

    assert g.batch_size == 1

    edgep_text = ''

    n = g.num_nodes()
    edgep_text += f'{n}\n'

    type_vec = g.ndata['h'][:, :-1] if 'h' in g.ndata.keys() else g.ndata['type']

    for i in range(n):
        types = type_vec[i].nonzero().numpy().flatten()
        t = ','.join([idx2phar[i] for i in types])
        edgep_text += f'{i + 1} {t}\n'

    dist_vec = g.edata['h'] if 'h' in g.edata.keys() else g.edata['dist']

    dist_mapping = {}
    for i, (u, v) in enumerate(torch.stack(g.edges()).T.numpy()):
        u, v = (u, v) if u < v else (v, u)
        dist_mapping[(u, v)] = dist_vec.numpy().flatten()[i]

    for (u, v), dist in dist_mapping.items():
        edgep_text += f'{u + 1} {v + 1} {dist}\n'

    if file_path is not None:
        assert file_path.suffix == '.edgep'
        file_path.write_text(edgep_text)

    return edgep_text
```

**Comment by miquelduranfrigola** [comment]
Thank you @CSUBioGroup - this is great stuff. Very useful!
